name: 8-bit
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=21.2.0
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.8
  - certifi=2021.10.8
  - cudatoolkit=11.1.74
  - ffmpeg=4.3
  - freetype=2.10.4
  - gmp=6.2.1
  - gnutls=3.6.13
  - iniconfig=1.1.1
  - intel-openmp=2021.4.0
  - jbig=2.1
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - lerc=2.2.1
  - libdeflate=1.7
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtiff=4.3.0
  - libuv=1.42.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - more-itertools=8.8.0
  - ncurses=6.2
  - nettle=3.6
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openh264=2.1.1
  - openssl=1.1.1l
  - packaging=21.0
  - pillow=7.2.0
  - pip=21.2.4
  - pluggy=0.13.1
  - py=1.10.0
  - pyparsing=2.4.7
  - pytest=6.2.4
  - python=3.9.7
  - python_abi=3.9
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - readline=8.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - toml=0.10.2
  - torchaudio=0.10.0
  - torchvision=0.11.1
  - typing_extensions=3.10.0.2
  - tzdata=2021a
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.5.0
